### ISSUE TITLE
Usage Instructions?

### ISSUE THREAD

**Issue by adonespitogo** [thredded/thredded-bbcode#1]
How, i tried installing it but nothing happens in my forum.

**Comment by glebm** [comment]
Did you restart the server?
You shouldn't need to do anything, simply adding this gem to the Gemfile should be enough to enable BBCode support.

**Comment by adonespitogo** [comment]
Sorry, I was expecting to see GUI elements in the comment box. I think this gem only parses input but do not provide GUI tol in views. Am I right?

**Comment by adonespitogo** [comment]
If not, I'd like to add a gui tool as a plugin to complement this gem. But I'm confused about Thredded's view hooks implementation.

**Comment by glebm** [comment]
> Sorry, I was expecting to see GUI elements in the comment box. I think this gem only parses input but do not provide GUI tol in views. Am I right?

Yeah no UI here.

There is an example of using view hooks here: https://github.com/thredded/thredded/wiki/Using-Thredded-with-Trix
